// ⚠️ 由 caijuehub/transcribe.ts 自动生成，不要手动编辑！
// 改 *-rules.toml 后重新运行: add-coder generate

// >>> CAIJUE GENERATED START >>>
export const DPS_SCORING_CONFIG = {
  SEMANTIC_WEIGHTS: [0.35, 0.45, 0.08, 0.12],
  SEMANTIC_MISSING_REVIEW_PENALTY: 0,
  ENTROPY_GAP_MULT: 10,
  DENG_PER_MARKER: 0.05,
  DENG_MAX_PENALTY: 0.3,
  MISSING_SPECS_GAP: 10,
  CPM_SUB_WEIGHTS: [0.4, 0.35, 0.25],
  CPM_OVERLAP_MULT: 2,
  CPM_MAX_TASK_PAIRS: 200,
  CPM_FILE_LOW: 3,
  CPM_FILE_MID: 5,
  CPM_ENTROPY_LOW: 6,
  CPM_ENTROPY_MID: 8,
  CPM_ATTENTION_WEIGHTS: [0.5, 0.5],
  CPM_DEP_WEIGHTS: [0.6, 0.4],
  STRUCT_PLACEHOLDER: 15,
  STRUCT_MISSING_SPECS: 30,
  STRUCT_MISSING_TASKS: 15,
  STRUCT_MISSING_CHECKLIST: 15,
  STRUCT_SUB_WEIGHTS: [0.6, 0.4],
  FFT_COLD_START: 5,
  FFT_HISTORY_LIMIT: 50,
  FFT_DEFAULT_WEIGHTS: [0.25, 0.25, 0.25, 0.25],
  THRESHOLD_PASS: 80,
  THRESHOLD_WARN: 65,
  EMBEDDING_MODEL: 'Xenova/bge-small-zh-v1.5',
} as const;
// <<< CAIJUE GENERATED END <<<
